# Run `ghostty +show-config --default --docs` to view a list of
# all available config options and their default values.

cursor-style = bar

# theme = BirdsOfParadise
# theme = Breeze
theme = Monokai Pro Spectrum

command = nu

font-size = 10

keybind = ctrl+shift+left=unbind
keybind = ctrl+shift+right=unbind

# cursor-color = #faf6f0
adjust-cursor-thickness = 2
