[helpers]

[default]
depends = []

[default.files]
gdbinit = "~/.gdbinit"
gitconfig = "~/.gitconfig"
nano = "~/.nano"
nanorc = "~/.nanorc"
"nushell.nu" = "~/.config/nushell/config.nu"

[default.variables]

[settings]
default_target_type = "automatic"
