[helpers]

[default]
depends = []

[default.files]
gdbinit = "~/.gdbinit"
gitconfig = "~/.gitconfig"
"micro.json" = "~/.config/micro/settings.json"
nano = "~/.nano"
nanorc = "~/.nanorc"
"nushell.nu" = "~/.config/nushell/config.nu"
zshrc = "~/.zshrc"

[default.variables]

[settings]
default_target_type = "automatic"
